services:
  api:
    build:
      context: .
    container_name: property_api
    restart: unless-stopped
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    volumes:
      - /app/node_modules
    command: sh -c "yarn start"
    networks:
      - rentio_network

networks:
  rentio_network:
    driver: bridge
    external: false
